/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DungeonRouteImport } from './routes/dungeon'
import { Route as CreateRouteImport } from './routes/create'
import { Route as CodexRouteImport } from './routes/codex'
import { Route as ChroniclerRouteImport } from './routes/chronicler'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DungeonRoute = DungeonRouteImport.update({
  id: '/dungeon',
  path: '/dungeon',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CodexRoute = CodexRouteImport.update({
  id: '/codex',
  path: '/codex',
  getParentRoute: () => rootRouteImport,
} as any)
const ChroniclerRoute = ChroniclerRouteImport.update({
  id: '/chronicler',
  path: '/chronicler',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chronicler': typeof ChroniclerRoute
  '/codex': typeof CodexRoute
  '/create': typeof CreateRoute
  '/dungeon': typeof DungeonRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chronicler': typeof ChroniclerRoute
  '/codex': typeof CodexRoute
  '/create': typeof CreateRoute
  '/dungeon': typeof DungeonRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chronicler': typeof ChroniclerRoute
  '/codex': typeof CodexRoute
  '/create': typeof CreateRoute
  '/dungeon': typeof DungeonRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chronicler'
    | '/codex'
    | '/create'
    | '/dungeon'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chronicler' | '/codex' | '/create' | '/dungeon' | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/chronicler'
    | '/codex'
    | '/create'
    | '/dungeon'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChroniclerRoute: typeof ChroniclerRoute
  CodexRoute: typeof CodexRoute
  CreateRoute: typeof CreateRoute
  DungeonRoute: typeof DungeonRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dungeon': {
      id: '/dungeon'
      path: '/dungeon'
      fullPath: '/dungeon'
      preLoaderRoute: typeof DungeonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codex': {
      id: '/codex'
      path: '/codex'
      fullPath: '/codex'
      preLoaderRoute: typeof CodexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chronicler': {
      id: '/chronicler'
      path: '/chronicler'
      fullPath: '/chronicler'
      preLoaderRoute: typeof ChroniclerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChroniclerRoute: ChroniclerRoute,
  CodexRoute: CodexRoute,
  CreateRoute: CreateRoute,
  DungeonRoute: DungeonRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
